OPENAI_API_KEY = "sk-proj-xfCD7cO8wCiTseACJnQdT3BlbkFJeRlXCgqv5t3OKzl0sx5J"

[AZURE_OPENAI]
AZURE_OPENAI_API_VERSION = "2024-02-15-preview"
AZURE_OPENAI_ENDPOINT="https://anv2dev-azureopenai-auseast.openai.azure.com/"
AZURE_OPENAI_APIKEY="685158aec57747dfad586110be180657" 
DEPLOYMENT_NAME = "anv2dev-gpt35turbo1106-auseast"
